### ISSUE TITLE
Can fart.exe use regular expressions?

### ISSUE THREAD

**Issue by geri777** [lionello/fart-it#11]
Hi, can I use regular expressions with this tool? If so, could you please show an example? Many thanks!

I have tried to rename files with this command:

`fart -f -p *.pdf [\d]{14} _`

So I want to replace 14-digit numbers in the filename with one underscore.
Nothing has been replaced: `Replaced 0 occurence(s) in 0 file(s).`

Then I tried with -C option. 
`fart -f -p -C *.pdf [\d]{14} _`

Then I get the message 
`Warning: unrecognized character escape sequence: \d`

Next thing I tried was to replace \d with 0-9
`fart -f -p -C *.* [0-9]{14} _`

The result was again: `Replaced 0 occurence(s) in 0 file(s).`

**Comment by sergeevabc** [comment]
Err… @lionello, hello?

**Comment by lionello** [comment]
Oh hey, sorry I missed this. No, regex is not supported and I don't have plans to add it. Personally I use `sed -i s/find/replace/g` for this.
