### ISSUE TITLE
how to use fart to replace multiple strings?

### ISSUE THREAD

**Issue by maravento** [lionello/fart-it#17]
how to use fart to replace multiple strings?. Executing a command for each replacement is not something very optimized

```
fart.exe out.txt "1a" "foo"
fart.exe out.txt "2b" "bar"
fart.exe out.txt "3c" "xyz"
```
Can this be reduced to 1 single command (or loop or read a list)? thk

**Comment by lionello** [comment]
Sorry, not something I plan to add. Multiple runs should work fine (if you take care of a search pattern appearing in a prior replace pattern). Otherwise, consider using `sed` which supports in-place replacements and multiple scripts.
