### ISSUE TITLE
Please include binaries in release zips

### ISSUE THREAD

**Issue by jamesford42** [lionello/fart-it#3]

**Comment by Gabr-F** [comment]
Yes it would be better, but compilation is very easy in any case, in my case I just had to launch its mk.bat from a Visual Studio 2010 Express prompt.

**Comment by b-degryse** [comment]
It might be very easy for you, but I'm sure for most people compiling is out of the question.
The least that should be done is give very clear instructions on how to do it, but even then it's probably a bridge too far for most.
So, please do publish executables!

**Comment by bernardoadc** [comment]
If someone has Visual Studio to build it, probably wouldn't even need FART at all. IMHO this is meant to be a simple app that just do the job, portable, easy. If you have to go down that path.. just use another solution
