### ISSUE TITLE
Issue with "//" in replacement string

### ISSUE THREAD

**Issue by thdoan** [lionello/fart-it#9]
Steps to reproduce:

`fart script.js "if (DEBUG" "//if (DEBUG"`

My workaround for now (adding space before "//"), but hope it can be fixed:

`fart script.js "if (DEBUG" " //if (DEBUG"`

**Comment by icnocop** [comment]
I think you have to escape a forward slash with a backslash.

For example `\/\/if (DEBUG`

**Comment by lionello** [comment]
Because on Windows `/` can be used to the short command line options, you have to use `--` if you want to use it as the prefix for the search or replace string:

```
fart script.js "if (DEBUG" -- "//if (DEBUG"
```

**Comment by lionello** [comment]
The command interpreter removes the double quotes so the application doesn’t know there were quotes around it. I’ll add a note about the — to the help. Good idea.
